## Docker compose para criar uma imagem do Wordpress e conectar com um banco de dados MySQL
volumes:
  dbdados:
  app_wp:

networks:
  webapp_net:
    driver: bridge


services: # Definição dos serviços.
  WP:
    image: wordpress:6.5.3-php8.1-apache
    ports:
      - 8080:80
    volumes:
      - app_wp:/var/www/html
    environment:
      - WORDPRESS_DB_NAME= ${MYSQL_DATABASE}
      - WORDPRESS_DB_HOST=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER= ${USER_WP}
      - WORDPRESS_DB_PASSWORD= ${MYSQL_PASSWORD}
    networks:
      - webapp_net

  dbdados:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdados:/var/lib/mysql
    networks:
      - webapp_net
    